development:
  vision_project_id: PROJECT_ID
  google_storage_access_key_id: GOOGLE_ID
  google_storage_secret_access_key:	GOOGLE_KEY
  bucket_name: insta-sx-development
  db_database: insta-xs_development
  db_password:
  db_username:
  redis_url: redis://localhost:6379/1
  default_host: localhost:4000

test:
  vision_project_id: qwerty
  google_storage_access_key_id: GOOGLEID
  google_storage_secret_access_key:	GOOGLEKEY
  bucket_name: insta-sx-test
  db_database: insta-xs_test
  db_password:
  db_username:
  redis_url: redis://localhost:6379/1
  default_host: localhost:4000
