default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  username: <%= Figaro.env.db_username %>
  password: <%= Figaro.env.db_password %>

development:
  <<: *default
  database: <%= Figaro.env.db_database %>

test:
  <<: *default
  database: <%= Figaro.env.db_database %>

production:
  <<: *default
  database: <%= Figaro.env.db_database %>
